import { REGISTER_START, REGISTER_SUCCESS, REGISTER_FAILURE } from './RegisterActions';
import { LOGIN_START, LOGIN_SUCCESS, LOGIN_FAILURE } from './LoginActions';


export {
    REGISTER_START,
    REGISTER_SUCCESS, 
    REGISTER_FAILURE,
    LOGIN_START,
    LOGIN_SUCCESS,
    LOGIN_FAILURE
};